
INSERT INTO home_Courses (course_code, course_title, department) values ('CHEM 001C','Chemistry for Engineers','Computer Engineering'), 
                                                                        ('CPE 003','Computer-Aided Drafting','Computer Engineering'), 
                                                                        ('CPE 007','Programming Logic and Design','Computer Engineering'), 
                                                                        ('CPE 008','Computer Engineering as a Discipline','Computer Engineering'), 
                                                                        ('CPE 201A','Computer System Administration and Troubleshooting','Computer Engineering'), 
                                                                        ('MATH 006','Discrete Mathematics','Computer Engineering'), 
                                                                        ('MATH 016','Calculus 1','Computer Engineering'), 
                                                                        ('CPE 009','Object Oriented Programming','Computer Engineering'), 
                                                                        ('GEC 004','Mathematics in the Modern World','Computer Engineering'), 
                                                                        ('GEE 001','General Education Elective 1','Computer Engineering'), 
                                                                        ('MATH 013','Linear Algebra with MATLAB','Computer Engineering'), 
                                                                        ('MATH 017','Calculus 2','Computer Engineering'), 
                                                                        ('MATH 019A','Engineering Data Analysis','Computer Engineering'), 
                                                                        ('PHYS 001C','Calculus-Based Physics','Computer Engineering'), 
                                                                        ('CPE 010','Data Structures and Algorithms','Computer Engineering'), 
                                                                        ('CPE 011','Database Management System','Computer Engineering'), 
                                                                        ('CPE 012','Data and Digital Communications','Computer Engineering'), 
                                                                        ('ECE 027','Fundamentals of Electronic Circuits','Computer Engineering'), 
                                                                        ('EE 041','Fundamentals of Electrical Circuits','Computer Engineering'), 
                                                                        ('EECO 001','Engineering Economics','Computer Engineering'), 
                                                                        ('MATH 010','Differential Equations','Computer Engineering'), 
                                                                        ('TECH 101','Introduction to Engineering Entrepreneurship','Computer Engineering'), 
                                                                        ('CPE 013','Logical Circuits and Design','Computer Engineering'), 
                                                                        ('CPE 014','Embedded Systems','Computer Engineering'), 
                                                                        ('CPE 302','Computer Networks 1','Computer Engineering'), 
                                                                        ('CPE 304','Computer Engineering Drafting and Design','Computer Engineering'), 
                                                                        ('CPE 311','Computational Thinking with Python','Computer Engineering'), 
                                                                        ('GEE 002','General Education Elective 2','Computer Engineering'), 
                                                                        ('MATH 020','Numberical Methods','Computer Engineering'), 
                                                                        ('CPE 015','Optimization Techniques','Computer Engineering'), 
                                                                        ('CPE 016','Introduction to HDL','Computer Engineering'), 
                                                                        ('CPE 017','Fundamentals of Mixed Signals and Sensors','Computer Engineering'), 
                                                                        ('CPE 018','Emerging Technologies 1 in CpE','Computer Engineering'), 
                                                                        ('CPE 312','Predictive Analytics using Machine Learning','Computer Engineering'), 
                                                                        ('CPE 401','Computer Networks 2','Computer Engineering'), 
                                                                        ('ECE 028','Feedback and Control Systems','Computer Engineering'), 
                                                                        ('CPE 019','Emerging Technologies 2 in CpE','Computer Engineering'), 
                                                                        ('CPE 020','Methods of Research','Computer Engineering'), 
                                                                        ('CPE 021','Computer Architecture and Organization','Computer Engineering'), 
                                                                        ('CPE 022','Operating Systems','Computer Engineering'), 
                                                                        ('CPE 023','CpE Laws and Professional Practice','Computer Engineering'), 
                                                                        ('CPE 313','Advanced Machine Learning and Deep Learning','Computer Engineering'), 
                                                                        ('CPE 404','Computer Networks 3','Computer Engineering'), 
                                                                        ('CPE 006','Microprocessor Systems','Computer Engineering'), 
                                                                        ('CPE 026','Emerging Technologies 3 in CpE','Computer Engineering'), 
                                                                        ('CPE 025','Software Design','Computer Engineering'), 
                                                                        ('CPE 028','Developing Applications and Automation','Computer Engineering'), 
                                                                        ('CPE 029','CpE Design Project 1','Computer Engineering'), 
                                                                        ('CPE 502','Plant Visits and Seminard for CPE','Computer Engineering');