# Generated by Django 4.1.2 on 2022-10-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor',
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseInformation', to='home.courses')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseInstructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
