# Generated by Django 4.1.2 on 2022-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_manual',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='ilo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab_manual',
            name='supplementary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
