# Generated by Django 4.1.2 on 2022-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_courses_instructor_courseinstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
