# Generated by Django 4.1.2 on 2022-10-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_courses_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab_manual',
            old_name='course_code',
            new_name='course',
        ),
    ]
