# Generated by Django 4.1.2 on 2022-10-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_course_code_lab_manual_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_code',
            new_name='course',
        ),
    ]
