# Generated by Django 4.1.2 on 2022-10-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_course_code_courses_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course',
            new_name='course_code',
        ),
    ]
