# Generated by Django 4.1.2 on 2022-10-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_course_courses_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_manual',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courseinformation', to='home.courseinstructor'),
        ),
    ]
